[theme]
primaryColor = "#34E0A1"
backgroundColor = "#0B0B10"
secondaryBackgroundColor = "#14141B"
textColor = "#F4F4F6"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false

[client]
showSidebarNavigation = false
